version: '3.7'
services: 
    app:
      platform: 'linux/amd64'
      env_file:
        - frontend/.env
      build:
        context: .
        dockerfile: Dockerfile.dev
      volumes:
        - /app/node_modules/
        - /app/.next
        - ./frontend/app:/app/app:rw
        - ./frontend/components:/app/components:rw
        - ./frontend/hooks:/app/hooks:rw
        - ./frontend/pages:/app/pages:rw
        - ./frontend/public:/app/public:rw
      ports:
        - 3000:3000