FROM node:16.17-alpine

RUN apk add --no-cache git build-base openssh
ENV PYTHONUNBUFFERED=1
RUN apk add --update --no-cache python3 && ln -sf python3 /usr/bin/python
RUN python3 -m ensurepip
RUN pip3 install --no-cache --upgrade pip setuptools

WORKDIR /app

ADD frontend .

RUN npm install --legacy-peer-deps

CMD npm run dev
