version: '3.7'
services: 
    app:
      platform: 'linux/amd64'
      env_file:
        - frontend/.env
      build:
        context: .
        dockerfile: Dockerfile.dev
      volumes:
        - ./frontend:/app/:rw
        - ./frontend/node_modules:/app/node_modules/
        - ./frontend/.next:/app/.next
      ports:
        - 3000:3000